plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.17.19'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
    withSourcesJar()
}

sourceSets.main.java.srcDir('../fabric-common/src/main/java')
sourceSets.main.resources.srcDir('../fabric-common/src/main/resources')

loom {
    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = 'minecraft_websocket_tunnel-refmap.json'
    }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.20.1'
    mappings 'net.fabricmc:yarn:1.20.1+build.10:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.16.14'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.92.6+1.20.1'
    implementation project(':core')
    include project(':core')
    include 'org.java-websocket:Java-WebSocket:1.5.7'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand(version: project.version, minecraft_dependency: '1.20.1') }
}
